name = "Magical Relics Modpack"
author = "itz_Jana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a79f1612ef7319d62d46729c974e155f73af4f1939b9f0ca9a8c69459e005a8"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
