name = "Magical Relics Modpack"
author = "itz_Jana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaceea78b9b573fc1f71f28cc05e27d1074236bc1bcf73e05086a7687d253e7c"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
