name = "Magical Relics Modpack"
author = "itz_Jana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdccfc39b2f32e7cf0835a43c519dee3e0d0b9a196ffac2fb6e3301f5d2f2e15"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
