name = "Magical Relics Modpack"
author = "itz_Jana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "873da90d728f29ce6d35d2bbee9aeb69d7d030d784cf1bf2d81fa1e0c89018de"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
