name = "Magical Relics Modpack"
author = "itz_Jana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c12cc613373abd5257f2f372c47eed0f071e66775ef2634035719109c8b162a"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
