name = "Magical Relics Modpack"
author = "itz_Jana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "143e8c57784516651ef40c30b7e22532ce5e8dc06268440ceb224bde44e47b21"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
