name = "Magical Relics Modpack"
author = "itz_Jana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0d0fe11523ff788ff6b1c1daa658f86cde679f9438a823af29a6038e78ec314"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
