name = "Magical Relics Modpack"
author = "itz_Jana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "329cfc3fd3b667b1b2f94b01d7ead255044f2854c5baa7231aec91a9e7a3f9c7"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
