name = "Magical Relics Modpack"
author = "itz_Jana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc1fd592dc83a8e517f5e37a8954ccc2477a9a4ce474c58ad187a1f5889aba14"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
