name = "Magical Relics Modpack"
author = "itz_Jana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6257aebf253e9e75135a3f573b4245ef94dc9837655b67d444051b871fcc4d3"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
