name = "Magical Relics Modpack"
author = "itz_Jana"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2367994d4678775ec48056d72691becefa62ad3f2fc1c3df6e4507ec6306441"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
